version: "3.9"

services:
  api-core:
    container_name: 65SA-api-core
    hostname: 65SA-api-core
    build: ./build/api-python
    volumes:
      - ./proj/api-core:/code/app #Replace application
      - ./ssl/current:/code/ssl #Replace key.pem & cert.pem
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # command: uvicorn app.main:app --host 0.0.0.0 --port 443 --ssl-keyfile=./ssl/key.pem --ssl-certfile=./ssl/cert.pem --reload
    ports:
      - "8000:8000"
      # - "443:443"

  db-mongo:
    container_name: 65SA-db-mongo
    hostname: 65SA-db-mongo
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db_65SA:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: 65SA-mongo-express
    hostname: 65SA-mongo-express
    image: mongo-express #1.0.0-alpha.4
    depends_on:
      - db-mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db-mongo:27017/

  web-platform:
    container_name: web-platform
    hostname: web-platform
    image: nginx:1.22-alpine
    working_dir: /etc/nginx
    ports:
      - 8001:80
    volumes:
      - ./proj/web-platform:/usr/share/nginx/html
